defaults/main.yml

The key used in the vhosts.j2 template is extra_parameters.

Fix nginx_vhosts comment

---

templates/nginx.conf.j2
vars/Debian.yml
vars/RedHat.yml

For Debian systems both conf.d and sites-enabled should be included by default. Redhat systems have not been changed.
Issues came up using Kibana on Ubuntu as it installs kibana.conf in the conf.d folder.

Added additional nginx_conf_path for Debian

---

templates/vhosts.j2

Remove semicolon after `{{ vhost.extra_parameters }}` to allow support for blocks like
```
location ~ \.php$ {
...
}
```
which would otherwise fail with a trailing semicolon.

Remove unnecessary semicolon from vhosts config

---

templates/vhosts.j2

There are instances where `root` isn't needed - for example, if I'm adding a server block to redirect from HTTP to HTTPS.
This PR makes `root` optional, and only adds it to the vhost if it's been added.

Only add root if it's defined

---

README.md
defaults/main.yml
handlers/main.yml
tasks/main.yml
tasks/vhosts.yml
templates/nginx.conf.j2

Hey Jeff!
Thanks for the great role :+1:
Hoping you'll happily accept these contributions (with any modifications you see fit, of course).
These changes bring a collective validation of the deployed Nginx configuration and the option to define arbitrary "extra" configuration options for the top-level `http` block in `/etc/nginx.conf`.
1. Nginx master config validation: I added a `validate` param on the deployment of the `/etc/nginx.conf` file. This will ensure the Nginx config (including any included configs) are valid, according to `nginx -t`. I had to move the deployment of vhosts above the deployment of the `nginx.conf` file, to ensure all config was in place before testing (see my commit message on cc5114d for more details).
2. Nginx config validation handler: I added a handler that …

Collective config validation & "extra options"

---

handlers/main.yml
tasks/main.yml
tasks/vhosts.yml

NOTE: current nginx config validation process breaks SELinux context
for pid file, as described in #41
Restart of nginx is not needed for configuration changes and is
replaced with reload, which will validate config before applying it,
leaving running nginx process untouched in case of any validation
errors.
Restart handler left in support.

Remove new config validation, Fix #41

---

defaults/main.yml
tasks/setup-Debian.yml
templates/nginx.conf.j2

Option that allows to define options within nginx's main context.
Option that allows to define nginx's package name.

Define package name and options within main context

---

templates/nginx.conf.j2

Restore default naming scheme for nginx's `sites-enabled`.
Default names for symlinks in `sites-enabled` are plain names without `.conf` extension. Default vhost name is `default`, but currently the role does not recognize it leading to "webpage not available" error on completion.
(basically revert 50% of [restore compartability with geerlingguy-kibana](https://github.com/geerlingguy/ansible-role-nginx/commit/d209cbe89ac3f19968e7292fa678606bd17ba133) commit)

Restore nginx's default search pattern for sites-enabled

---

templates/nginx.conf.j2
vars/Debian.yml
vars/RedHat.yml

The packaged version of nginx.conf sets the pid file to /run/nginx.pid. When the pid value is changed and nginx receives the reload signal, the pid file gets removed. This causes 'service: name=nginx state=started enabled=yes' to think nginx is down on subsequent ansible runs.
See https://trac.nginx.org/nginx/ticket/796 for more info.
This PR creates a 'nginx_pidfile' role var in order to change the nginx.conf.j2 pid for Debian hosts.

changing Debian pidfile

---

defaults/main.yml
tasks/main.yml
tasks/setup-Ubuntu.yml
tests/test.yml

adds ppa:nginx to apt repositories when
nginx_use_ppa is set to true (default false)
nginx_ppa_version can be either "stable" or "development"
this will reinstall nginx if ppa was just added to ensure that the ppa
version will be installed
fixes Issue #27

add official nginx ppa for ubuntu

---

templates/vhosts.j2

An nginx server block does not require a `server_name`, so no need to enforce that in this package. A use case is a "no default" setup, as recommended by the [HTML5 Boilerplate](https://html5boilerplate.com/) project:
https://github.com/h5bp/server-configs-nginx/blob/3921535db8b9123432fe11a18842989c48fe7b07/sites-available/no-default

make the "server_name" directive optional

---

templates/nginx.conf.j2
templates/vhosts.j2

By using Jinja2's [whitespace control features](http://jinja.pocoo.org/docs/dev/templates/#whitespace-control), we can make the generated nginx templates much more pleasant to read. For example:
```
server {
listen 80 default_server;
return 444;
}
server {
listen 80;
server_name example.com;
return 301 $scheme://www.example.com$request_uri;
}
server {
listen 80;
server_name www.example.com;
root /var/www/example.com/public;
index index.html;
}
```
```
server {
listen 80 default_server;
return 444;
}
server {
listen 80;
server_name example.com;
return 301 $scheme://www.example.com$request_uri;
}
server {
listen 80;
server_name www.example.com;
root /var/www/example.com/public;
index index.html;
}
```

prevent whitespace from jinja control structures from making it into templates

---

defaults/main.yml
tasks/vhosts.yml

It allows to configure vhosts filename with `nginx_vhosts_filename` variable. It defaults "vhosts.conf". (See #61).

Add nginx_vhosts_filename variable to allow multiple managed files

---

README.md
templates/vhosts.j2

Previously, one needed to extra-indent subsequent lines by 4 spaces.
This changes makes reading the configuration in yaml much more
pleasant.

Fix unnatural indentation in extra_parameters block

---

tasks/vhosts.yml

In particular, the `/usr/local/etc/nginx/sites-enabled` directory does not exist on a fresh install of Nginx on FreeBSD, and the template task doesn't ensure it will.

Create the Nginx vhost path directory

---

templates/nginx.conf.j2

http section in nginx.conf is indented by default. To increase
readability format the variable nginx_extra_http_options with
the same indent for multiline string blocks. Therefore indent
needs not to be done in yaml.

format nginx_extra_http_options with indent

---

tasks/vhosts.yml

My system : Debian.
After the installation of Nginx, the service is up and running. So, by default, the process listen to (and lock)  0.0.0.0:80.
If you set `nginx_remove_default_vhost: true`, reloading is not enough to release the lock. The ansible role has to restart the nginx.
Let me expose a use case, on the same server, the nginx has to listen to 127.0.0.1:80 and the Haproxy to <eth_ip>:80. A lock on 0.0.0.0:80 causes a fail of the playbook apply.

Restart instead of reload after remove default.

---

defaults/main.yml
tasks/setup-RedHat.yml

In environments where RHEL uses Satellite or production servers can't
reach out to the internet, and the Yum repo is not wanted. This commit
adds a flag to disable the functionality. It also removes the
enablerepo: nginx line from the package since a) it's redundant and b)
working around it overly complicates  the situation.

adding yum repo flag for Redhat

---

defaults/main.yml
templates/nginx.conf.j2

`geerlingguy.nginx` prevents `log_format` customization. nginx triggers an emergency error on twice declaration of log_format. So we should allow to customize this. What do you think of this ?

Parametrize log_format

---

README.md
defaults/main.yml
tasks/main.yml
tasks/vhosts.yml
templates/nginx.conf.j2
templates/vhost.j2

This is just a POC of allowing template files to be overridden. It's based on #91 so only the last commit actually belongs to this PR.
Should we also add  basic out of the box support for SSL?

Template inheritance

---

README.md
defaults/main.yml
tasks/vhosts.yml
tests/test.yml

One solution of how we could fix the problem brought forward here https://github.com/geerlingguy/ansible-role-nginx/pull/91#issuecomment-305544257. Currently it's not possible to create a redirect from http -> https as the domain names would be identical and therefore the second vhost file would overwrite the first one.
I also improved the README example so it shows a more advanced, but very common scenario where you want to redirect all http traffic to https, as well as redirect www.example.com to example.com.
Any better ideas?

Followup #91: Add `filename` option `nginx_vhosts`

---

templates/vhost.j2

Add missing server {  to vhost template
This should fix #106

fix vhost.j2

---

tasks/main.yml

As 'include' will be deprecated in ansible version 2.8, it needs to be replaced by 'import_tasks' and 'include_tasks'

Changed 'include' to 'import_tasks' and 'include_tasks'

---

tasks/setup-RedHat.yml

I noticed that your other roles have switched to using the package module instead of yum.

Use package module instead of yum

---

defaults/main.yml

This converts the example value of nginx_upstreams.servers to a simple list of backends instead of using the unusual object syntax.

Fix documented example value for nginx_upstreams.servers

---

tasks/setup-Ubuntu.yml

In one task (tasks/setup-Ubuntu.yml), looks like it was forgotten to change the name of package to the variable. I fixed it.

change fixed apt package name to var nginx_package_name

---

handlers/main.yml

If we use the role with variable `nginx_service_state: "stopped"`, the handler shouldn't run.

fix(handler):not run handler when nginx_service_state stopped

---

.github/workflows/ci.yml
.gitignore
README.md
defaults/main.yml
tasks/main.yml
tasks/setup-Suse.yml
vars/Suse.yml

Hi, this PR adds support for openSUSE Leap and SLES 15.

feat: support suse
